### ISSUE TITLE
bug: footer social links

### ISSUE THREAD

**Issue by wolovim** [Developer-DAO/website#9]
- twitter logo should be replaced with "X" logo
- twitter link is missing underscore, e.g., "developer_dao"
- github link is missing a dash in the name, e.g. "Developer-DAO"

**Comment by kempsterrrr** [comment]
thanks @wolovim being address in #10

**Comment by gordo-labs** [comment]
Seeing this now with the @kempsterrrr PR. Missed the email

**Comment by kempsterrrr** [comment]
Closed in #10
